all:
	gcc main.c -DVERSION=0 -o serial
	gcc main.c -DVERSION=1 -o spin
	gcc main.c -DVERSION=2 -o mutex
	gcc main.c -DVERSION=3 -o cas
	gcc main.c -DVERSION=4 -o backoff
	gcc main2.c -DVERSION=0 -o serial2
	gcc main2.c -DVERSION=1 -o spin2
	gcc main2.c -DVERSION=2 -o mutex2
	gcc main2.c -DVERSION=3 -o cas2
	gcc main2.c -DVERSION=4 -o backoff2
